name: CI

on: [push]

jobs:
  build-wsl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        working-directory: client
        run: cargo build --release

      - name: Strip Debug Symbols
        run: strip target/release/wsld

      - uses: actions/upload-artifact@v2
        with:
          name: 'wsld'
          path: target/release/wsld

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/wsld
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        working-directory: server
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: 'wsldhost.exe'
          path: target/release/wsldhost.exe

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/wsldhost.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
